### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by javashin** [Snikii/Lenovo-Thinkpad-L440#1]
How I Can Use This Overlay /? any instructions ?

**Comment by javashin** [comment]
??????? sorry to bother but can i have an answer please

**Comment by Sniki** [comment]
Hi @javashin 

Sorry for the long wait because i was working bit by bit on the macOS Mojave guide and i thought it will be ready but took too long as life has been very busy for me recently.

I had the macOS Sierra and High Sierra guides but they were very outdated.

Here is the macOS Mojave guide for Lenovo ThinkPad L440:
[https://www.tonymacx86.com/threads/guide-lenovo-thinkpad-l440-using-clover-uefi-hotpatch.279912/](url)

If you have any further questions, please use the forum.

Will close this issue.

Enjoy !

**Comment by javashin** [comment]
Omg Thanks 
Thanks u so much
